### ISSUE TITLE
Broken by Dart 1.12-dev

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/source_gen#53]
See https://travis-ci.org/dart-lang/source_gen/jobs/69027291

```
AnalysisException: <rethrow>
  Caused by The null object does not have a getter 'importsAndExports'.

  NoSuchMethodError: method not found: 'importsAndExports'
  Receiver: null
  Arguments: []
  #0      AnalysisTask._safelyPerform (package:analyzer/src/generated/engine.dart:6434:7)
  #1      AnalysisTask.perform (package:analyzer/src/generated/engine.dart:6403:7)
  #2      AnalysisContextImpl._cacheDartResolutionData (package:analyzer/src/generated/engine.dart:2804:12)
  #3      AnalysisContextImpl._getDartResolutionData (package:analyzer/src/generated/engine.dart:3413:17)
  #4      AnalysisContextImpl._getDartResolutionData2 (package:analyzer/src/generated/engine.dart:3442:14)
  #5      AnalysisContextImpl.computeLibraryElement (package:analyzer/src/generated/engine.dart:1692:7)
  #6      _getLibraryElement (package:source_gen/src/utils.dart:170:20)
  #7      _getLibraryElements.<anonymous closure> (package:source_gen/src/utils.dart:183:20)
  #8      MappedListIterable.elementAt (dart:_internal/iterable.dart:413)
  #9      ListIterator.moveNext (dart:_internal/iterable.dart:341)
  #10     WhereIterator.moveNext (dart:_internal/iterable.dart:435)
  #11     List.List.from (dart:core-patch/array_patch.dart:44)
  #12     Iterable.toList (dart:core/iterable.dart:340)
  #13     getAnalysisContextForProjectPath.<getAnalysisContextForProjectPath_async_body> (package:source_gen/src/utils.dart:105:44)
  #14     Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
  #15     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:205:15)
  #16     StackZoneSpecification.registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:124:48)
  #17     _rootRun (dart:async/zone.dart:900)
  #18     _CustomZone.run (dart:async/zone.dart:803)
  #19     _CustomZone.runGuarded (dart:async/zone.dart:709)
  #20     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:734)
  #21     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:205:15)
  #22     StackZoneSpecification.registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:124:48)
  #23     _rootRun (dart:async/zone.dart:904)
  #24     _CustomZone.run (dart:async/zone.dart:803)
  #25     _CustomZone.runGuarded (dart:async/zone.dart:709)
  #26     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:734)
  #27     _microtaskLoop (dart:async/schedule_microtask.dart:43)
  #28     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
  #29     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
  #30     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

  Caused by The null object does not have a getter 'importsAndExports'.

  NoSuchMethodError: method not found: 'importsAndExports'
  Receiver: null
  Arguments: []
  #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
  #1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
  #2      LibraryResolver._addToDependencyMap (package:analyzer/src/generated/resolver.dart:7981:49)
  #3      LibraryResolver._addToDependencyMap (package:analyzer/src/generated/resolver.dart:7993:9)
  #4      LibraryResolver._addToDependencyMap (package:analyzer/src/generated/resolver.dart:7983:9)
  #5      LibraryResolver._computeDependencyMap (package:analyzer/src/generated/resolver.dart:8256:5)
  #6      LibraryResolver._computeLibrariesInCycles (package:analyzer/src/generated/resolver.dart:8299:9)
  #7      LibraryResolver.resolveLibrary (package:analyzer/src/generated/resolver.dart:7861:26)
  #8      ResolveDartLibraryTask.internalPerform (package:analyzer/src/generated/engine.dart:10538:15)
  #9      AnalysisTask._safelyPerform (package:analyzer/src/generated/engine.dart:6430:7)
  #10     AnalysisTask.perform (package:analyzer/src/generated/engine.dart:6403:7)
  #11     AnalysisContextImpl._cacheDartResolutionData (package:analyzer/src/generated/engine.dart:2804:12)
  #12     AnalysisContextImpl._getDartResolutionData (package:analyzer/src/generated/engine.dart:3413:17)
  #13     AnalysisContextImpl._getDartResolutionData2 (package:analyzer/src/generated/engine.dart:3442:14)
  #14     AnalysisContextImpl.computeLibraryElement (package:analyzer/src/generated/engine.dart:1692:7)
  #15     _getLibraryElement (package:source_gen/src/utils.dart:170:20)
  #16     _getLibraryElements.<anonymous closure> (package:source_gen/src/utils.dart:183:20)
  #17     MappedListIterable.elementAt (dart:_internal/iterable.dart:413)
  #18     ListIterator.moveNext (dart:_internal/iterable.dart:341)
  #19     WhereIterator.moveNext (dart:_internal/iterable.dart:435)
  #20     List.List.from (dart:core-patch/array_patch.dart:44)
  #21     Iterable.toList (dart:core/iterable.dart:340)
  #22     getAnalysisContextForProjectPath.<getAnalysisContextForProjectPath_async_body> (package:source_gen/src/utils.dart:105:44)
  #23     Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
  #24     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:205:15)
  #25     StackZoneSpecification.registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:124:48)
  #26     _rootRun (dart:async/zone.dart:900)
  #27     _CustomZone.run (dart:async/zone.dart:803)
  #28     _CustomZone.runGuarded (dart:async/zone.dart:709)
  #29     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:734)
  #30     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:205:15)
  #31     StackZoneSpecification.registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:124:48)
  #32     _rootRun (dart:async/zone.dart:904)
  #33     _CustomZone.run (dart:async/zone.dart:803)
  #34     _CustomZone.runGuarded (dart:async/zone.dart:709)
  #35     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:734)
  #36     _microtaskLoop (dart:async/schedule_microtask.dart:43)
  #37     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
  #38     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
  #39     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)


  package:analyzer/src/generated/engine.dart 2456:11            AnalysisContextImpl.recordResolveDartLibraryTaskResults
  package:analyzer/src/generated/engine.dart 4866:32            AnalysisContextImpl_AnalysisTaskResultRecorder.visitResolveDartLibraryTask
  package:analyzer/src/generated/engine.dart 10530:15           ResolveDartLibraryTask.accept
  package:analyzer/src/generated/engine.dart 6411:33            AnalysisTask.perform.<fn>
  package:analyzer/src/generated/utilities_general.dart 150:15  _PerformanceTagImpl.makeCurrentWhile
  package:analyzer/src/generated/engine.dart 6411:10            AnalysisTask.perform
  package:analyzer/src/generated/engine.dart 2804:12            AnalysisContextImpl._cacheDartResolutionData
  package:analyzer/src/generated/engine.dart 3413:17            AnalysisContextImpl._getDartResolutionData
  package:analyzer/src/generated/engine.dart 3442:14            AnalysisContextImpl._getDartResolutionData2
  package:analyzer/src/generated/engine.dart 1692:7             AnalysisContextImpl.computeLibraryElement
  package:source_gen/src/utils.dart 170:20                      _getLibraryElement
  package:source_gen/src/utils.dart 183:20                      _getLibraryElements.<fn>
  dart:core                                                     Iterable.toList
  package:source_gen/src/utils.dart 105:44                      getAnalysisContextForProjectPath.<async>
  ===== asynchronous gap ===========================
  dart:async                                                    _Completer.completeError
  package:source_gen/src/utils.dart 112:1                       getAnalysisContextForProjectPath.<async>
  ===== asynchronous gap ===========================
  dart:async                                                    Future.Future.microtask
  package:source_gen/src/utils.dart                             getAnalysisContextForProjectPath
  test/annotation_test.dart 242:23                              _getTestLibElement.<async>
  ===== asynchronous gap ===========================
  dart:async                                                    _Future.then
  test/annotation_test.dart 240:7                               _getTestLibElement.<async>
  ===== asynchronous gap ===========================
  dart:async                                                    Future.Future.microtask
  test/annotation_test.dart                                     _getTestLibElement
  test/annotation_test.dart 27:26                               main.<fn>.<async>
  ===== asynchronous gap ===========================
  dart:async                                                    Future.Future.microtask
  test/annotation_test.dart                                     main.<fn>
```

**Comment by bwilkerson** [comment]
It appears (just based on looking at the code) to ultimately be going wrong on this line:

    _addToDependencyMap(_asyncLibrary, dependencyMap, visitedLibraries);

because _asyncLibrary is `null`. This implies that analyzer could find the dart:async library, which would happen if the version of dartanalyzer being run is either newer or older than the version of the SDK being used to analyze the code. Is that a plausible explanation in this case? (If so, I'd like to understand the reason for the difference.)

**Comment by kevmoo** [comment]
Fixed!
