### ISSUE TITLE
Annotations do not support `Function`

### ISSUE THREAD

**Issue by tejainece** [dart-lang/source_gen#93]
Annotations do not support `Function`.
## Annotation class:

``` dart
class Interceptor {
  final Function interceptor;

  const Interceptor(this.interceptor);
}
```
## Usage of annotation:

``` dart
String interceptor(HttpRequest request) {
  return "I intercepted!";
}

@Group()
class TestApi extends Object with JaguarTestApi {
  int a = 12;

  @Route()
  @Interceptor(interceptor)
  String get() {
    return "data";
  }
}
```
## Creating instance from annotation in generator:

Calling `instantiateAnnotation` on this from generator throws an error:

``` dart
 var annotationInstance =
      instantiateAnnotation(matchingAnnotations.single) as Interceptor;
```
## The error:

```
Cannot create object from (HttpRequest) → String (interceptor)
#0      _getValue (package:source_gen/src/annotation.dart:115:3)
#1      _createFromConstructor (package:source_gen/src/annotation.dart:176:26)
#2      instantiateAnnotation (package:source_gen/src/annotation.dart:44:12)
```

**Comment by tejainece** [comment]
Adding the following if clause should fix this.

```dart
if (object.type == typeProvider.functionType) {
```

**Comment by matanlurey** [comment]
This API has changed drastically, and this is an FR from 2016, so closing for now.
